name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Node.js (server cache)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install & build server
        working-directory: server
        run: |
          npm ci
          # lint server sources - fail CI if lint errors
          npm run lint
          npm test
          npm run build

      - name: Start server (background)
        working-directory: server
        run: |
          # start the built server in background for E2E tests
          nohup npm start > server.log 2>&1 &

      - name: Setup Node.js (frontend cache)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install, typecheck & build frontend
        working-directory: frontend
        run: |
          # restore npm cache for frontend (handled by setup-node)
          npm ci
          # lint frontend sources - fail CI if lint errors
          npm run lint
          # run frontend tests
          npm test --silent
          # run TypeScript type check (no emit)
          npx tsc -p tsconfig.json --noEmit
          npm run build
          # start the dev server (supports proxy to backend) in the background for Playwright
          nohup npm run dev -- --port 5173 > preview.log 2>&1 &
          # wait for frontend to be available
          npx wait-on http://localhost:5173
          # install playwright browsers and run E2E tests
          npx playwright install --with-deps
          npx playwright test --config=playwright.config.ts --reporter=list
