name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Use Node 20 to match some devDependencies that require newer Node versions
          node-version: '20'

      - name: Setup Node.js (server cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install & build server
        working-directory: server
        run: |
          npm ci
          # lint server sources - fail CI if lint errors
          npm run lint
          npm test
          npm run build

      - name: Start server (background)
        working-directory: server
        run: |
          # start the built server in background for E2E tests
          nohup npm start > server.log 2>&1 &

      - name: Diagnostics after server start
        working-directory: server
        run: |
          # short sleep to let process spawn
          sleep 1
          echo "--- process list (node/npm) ---"
          ps aux | egrep "node|npm" || true
          echo "--- server.log head ---"
          head -n 200 server.log || true
          echo "--- server.log tail ---"
          tail -n 200 server.log || true
          echo "--- node/npm versions ---"
          node --version || true; npm --version || true
          echo "--- listening TCP ports (ss) ---"
          ss -ltnp || netstat -ltnp || true

      - name: Wait for server to be ready
        working-directory: server
        run: |
          # wait for the backend to accept connections, and show last logs for debugging
          # wait up to 2 minutes for backend to accept connections
          npx wait-on --timeout 120000 http://localhost:4000
          echo "--- server.log (tail) ---"
          tail -n +1 server.log || true

      - name: Setup Node.js (frontend cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install, typecheck & build frontend
        working-directory: frontend
        run: |
          # restore npm cache for frontend (handled by setup-node)
          npm ci
          # lint frontend sources - fail CI if lint errors
          npm run lint
          # run frontend tests
          npm test --silent
          # run TypeScript type check (no emit)
          npx tsc -p tsconfig.json --noEmit
          npm run build
          # start the dev server with explicit API base so it hits the backend directly in CI
          VITE_API_BASE=http://localhost:4000 nohup npm run dev -- --port 5173 > preview.log 2>&1 &
          # wait for frontend to be available
          # wait up to 2 minutes for frontend to be available
          npx wait-on --timeout 120000 http://localhost:5173
          # install playwright browsers and run E2E tests
          # Debug: print environment and check installed playwright packages to catch duplicates
          echo "--- Environment (selected vars) ---"
          env | sort | egrep "(HTTP|HTTPS|ALL_PROXY|NO_PROXY|VITE|PLAYWRIGHT|NODE)" || true
          echo "--- node/npm versions ---"
          node --version; npm --version
          echo "--- Check installed Playwright packages ---"
          npm ls @playwright/test playwright --long || true
          npx playwright install --with-deps
          # show last lines of preview and server logs for debugging
          echo "--- preview.log (tail) ---"; tail -n 200 preview.log || true
          echo "--- server.log (tail) ---"; tail -n 200 ../server/server.log || true
          # run Playwright tests via npm script to ensure resolution from package.json
          npm run e2e:ci
