name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install & build server
        working-directory: server
        run: |
          npm ci
          npm test
          npm run build

      - name: Start server (background)
        working-directory: server
        run: |
          # start the built server in background for E2E tests
          nohup npm start > server.log 2>&1 &

      - name: Install, typecheck & build frontend
        working-directory: frontend
        run: |
          npm ci
          # run frontend tests
          npm test --silent
          # run TypeScript type check (no emit)
          npx tsc -p tsconfig.json --noEmit
          npm run build
          # start a preview server in the background for Playwright
          nohup npm run preview -- --port 5173 > preview.log 2>&1 &
          # install playwright browsers and run E2E tests
          npx playwright install --with-deps
          npx playwright test --config=playwright.config.ts --reporter=list
